# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Adrian Gabor
email: adyle5@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  Currently a Lead Developer at Open Dealer Exchange, I have 18 years experience in IT at Pfizer, American Express, FPL, ADP and others. I am an MCP and a former adjunct instructor at Broward Community College. I have spent most of my career using Microsoft technologies, but I love open source software.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://wwww.adriangabor.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  adyle5

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
